packages:
  - "apps/*"
  - "packages/*"

catalogs:
  web:
    react: ^19.1.1
    "@types/react": ^19.1.9
    react-dom: ^19.1.1
    "@types/react-dom": ^19.1.7
    next: ^15.5.3
    next-themes: ^0.4.6
    better-auth: ^1.3.27
    tailwindcss: ^4.1.11
    "@tailwindcss/postcss": ^4.1.11
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-dialog": ^1.1.15
    "@radix-ui/react-dropdown-menu": ^2.1.16
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-slot": ^1.2.3
    "@radix-ui/react-tooltip": ^1.2.8
    input-otp: ^1.4.2
    lucide-react: ^0.475.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    tw-animate-css: ^1.3.6
    sonner: ^2.0.7
    resend: 4.5.1
    "@react-email/components": 0.5.6
    "@react-email/preview-server": 4.3.0
    react-email: 4.3.0
    react-hook-form: ^7.62.0
    "@hookform/resolvers": ^5.2.2
    "@tanstack/react-query": ^5.87.4
    qrcode: ^1.5.4
    "@types/qrcode": ^1.5.5

  server:
    express: ^5.1.0
    "@types/express": ^5.0.3
    cors: ^2.8.5
    "@types/cors": ^2.8.19
    helmet: ^8.1.0
    morgan: ^1.10.1
    "@types/morgan": ^1.9.10

  core:
    turbo: ^2.5.5
    zod: ^3.25.76
    dotenv: ^17.2.1
    prisma: ^6.16.1
    "@prisma/client": ^6.16.1
    date-fns: ^4.1.0
    "@upstash/ratelimit": ^2.0.6
    "@upstash/redis": ^1.35.5

  dev:
    typescript: ^5.9.2
    esbuild: ^0.20.1
    esbuild-register: ^3.5.0
    "@types/node": ^20.19.9
    tsx: ^4.19.2
    nodemon: ^3.1.10
    "@turbo/gen": ^2.5.5
    jest: ^30.1.3
    ts-jest: ^29.4.3
    supertest: ^7.1.4
    "@types/supertest": ^6.0.3
    "@jest/globals": ^30.1.2

  eslint:
    eslint: ^9.32.0
    eslint-config-prettier: ^9.1.2
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.5
    typescript-eslint: ^8.39.0
    globals: ^15.15.0
    "@eslint/js": ^9.34.0
    "@next/eslint-plugin-next": ^15.4.5
    "@typescript-eslint/eslint-plugin": ^8.39.0
    "@typescript-eslint/parser": ^8.39.0

  prettier:
    prettier: ^3.6.2
    prettier-plugin-organize-imports: ^4.1.0
    prettier-plugin-packagejson: ^2.5.10
    prettier-plugin-tailwindcss: ^0.6.11
