import { createHash } from "node:crypto";
import { readFile, writeFile, access, readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { toKebabCase } from "./utils.js";

export const MANIFEST_FILE = ".build-elevate.json";

export interface BuildElevateManifest {
  commit: string; // exact git SHA cloned from main — source of truth for upgrade comparisons
  template: string;
  projectName: string;
  scaffoldedAt: string;
  files: Record<string, string>; // filePath -> sha256 hash (first 12 chars)
}

export const hashContent = (content: string): string => {
  const normalized = content.replace(/\r\n/g, "\n");
  return createHash("sha256").update(normalized).digest("hex").slice(0, 12);
};

export const hashFile = async (filePath: string): Promise<string | null> => {
  try {
    const content = await readFile(filePath, "utf8");
    return hashContent(content);
  } catch {
    return null;
  }
};

export const manifestExists = async (): Promise<boolean> => {
  try {
    await access(MANIFEST_FILE);
    return true;
  } catch {
    return false;
  }
};

export const readManifest = async (): Promise<BuildElevateManifest | null> => {
  try {
    const content = await readFile(MANIFEST_FILE, "utf8");
    return JSON.parse(content) as BuildElevateManifest;
  } catch {
    return null;
  }
};

export const writeManifest = async (
  manifest: BuildElevateManifest,
): Promise<void> => {
  await writeFile(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");
};

/**
 * Directories and files to never hash.
 * These are either user-owned, generated, or environment-specific.
 */
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".turbo",
  ".next",
  "dist",
  "build",
  ".cache",
  "coverage",
  ".react-email",
  "generated/prisma",
  "scripts", // internal CLI — deleted by deleteInternalContent() anyway
  "assets", // internal — also deleted
  "apps/docs", // internal — also deleted
]);

const SKIP_FILES = new Set([
  // env files — user fills these in, never overwrite
  ".env",
  ".env.local",
  ".env.production",
  ".env.development",
  // lock files — regenerated by package manager
  "pnpm-lock.yaml",
  "bun.lockb",
  "package-lock.json",
  "yarn.lock",
  // tsconfig build info — environment-specific
  "tsconfig.scripts.json",
  "tsconfig.tsbuildinfo",
  // the manifest itself
  ".build-elevate.json",
  // internal files deleted during init
  "SCREENSHOTS.md",
  ".npmignore",
  "tsup.config.ts",
]);

const SKIP_EXTENSIONS = new Set([
  ".gz",
  ".zip",
  ".tar",
  ".tgz",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".svg",
  ".ico",
  ".webp",
  ".woff",
  ".woff2",
  ".ttf",
  ".eot",
  ".pdf",
  ".map",
]);

/**
 * Recursively walk the directory and return all file paths relative to the root,
 * excluding any in SKIP_DIRS or SKIP_FILES or with SKIP_EXTENSIONS.
 * Normalize all paths to use forward slashes for cross-platform consistency.
 */
const walkDir = async (
  dir: string,
  root: string,
  results: string[] = [],
): Promise<string[]> => {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    // Normalize to forward slashes for cross-platform consistency
    const relPath = relative(root, fullPath).replace(/\\/g, "/");

    if (entry.isDirectory()) {
      // Skip if the dir name itself is in SKIP_DIRS
      if (SKIP_DIRS.has(entry.name)) continue;
      // Skip if the relative path matches (e.g. "apps/docs")
      if (SKIP_DIRS.has(relPath)) continue;
      await walkDir(fullPath, root, results);
    } else if (entry.isFile()) {
      if (SKIP_FILES.has(entry.name)) continue;
      if (SKIP_FILES.has(relPath)) continue;
      const ext = entry.name.includes(".")
        ? "." + entry.name.split(".").pop()!
        : "";
      if (SKIP_EXTENSIONS.has(ext)) continue;
      results.push(relPath);
    }
  }

  return results;
};

/**
 * Build the manifest by hashing all relevant files in the project directory.
 * The manifest includes the commit hash, template name, project name, timestamp, and a mapping of file paths to their content hashes.
 * Only files that are not in SKIP_DIRS, SKIP_FILES, or with SKIP_EXTENSIONS are included.
 */
export const buildManifest = async (
  commit: string,
  template: string,
  projectName: string,
  projectRoot: string = process.cwd(),
): Promise<BuildElevateManifest> => {
  const allFiles = await walkDir(projectRoot, projectRoot);
  const files: Record<string, string> = {};

  await Promise.all(
    allFiles.map(async (filePath) => {
      const hash = await hashFile(join(projectRoot, filePath));
      if (hash !== null) {
        files[filePath] = hash;
      }
    }),
  );

  return {
    commit,
    template,
    projectName: toKebabCase(projectName),
    scaffoldedAt: new Date().toISOString(),
    files,
  };
};
